[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_BASE_URL = "https://ovov-web.netlify.app"
  NODE_VERSION = "20.11.1"

[[plugins]]
  package = "@netlify/plugin-nextjs" 